//
//  Aisles.swift
//  Recipes
//
//  Created by Chris Doornink on 1/8/18.
//  Copyright © 2018 Chris Doornink. All rights reserved.
//

import UIKit

struct Item {
    let word: String
    let aisle: String
}

struct FredMeyer {

    static let aisles = [
        "produce",
        "bulk",
        "liquor",
        "specialty",
        "spreads",
        "bread",
        "seafood",
        "snacks",
        "meat",
        "dairy",
        "cheese",
        "freezer",
        "baking",
        "cereal",
        "pasta",
        "beans",
        "soup",
        "cleaning",
        "babies",
        "personal",
        "medicine",
        "other",
    ]

    static let aisleDesignations = [
        // prefix catch all adjectives
        Item(word: "baking", aisle: "baking"),
        Item(word: "frozen", aisle: "freezer"),
        Item(word: "fresh", aisle: "produce"),
        Item(word: "alcohol", aisle: "liquor"),
        // regular
        Item(word: "7up", aisle: "snacks"),
        Item(word: "aceto", aisle: "medicine"),
        Item(word: "advil", aisle: "medicine"),
        Item(word: "agave", aisle: "produce"),
        Item(word: "allergy", aisle: "medicine"),
        Item(word: "applesauce", aisle: "baking"),
        Item(word: "artichoke heart", aisle: "beans"),
        Item(word: "arugula", aisle: "produce"),
        Item(word: "asparagus", aisle: "produce"),
        Item(word: "avocado", aisle: "produce"),
        Item(word: "bacon", aisle: "cheese"),
        Item(word: "baggette", aisle: "specialty"),
        Item(word: "baugette", aisle: "specialty"),
        Item(word: "balsamic", aisle: "pasta"),
        Item(word: "bananas", aisle: "produce"),
        Item(word: "band aid", aisle: "medicine"),
        Item(word: "bandaid", aisle: "medicine"),
        Item(word: "basil", aisle: "baking"),
        Item(word: "bb cr", aisle: "babies"),
        Item(word: "beef broth", aisle: "soup"),
        Item(word: "beef", aisle: "meat"),
        Item(word: "beer", aisle: "snacks"),
        Item(word: "berries", aisle: "produce"),
        Item(word: "berry", aisle: "produce"),
        Item(word: "bleach", aisle: "cleaning"),
        Item(word: "fancy bread", aisle: "specialty"),
        Item(word: "good bread", aisle: "specialty"),
        Item(word: "nice bread", aisle: "specialty"),
        Item(word: "bourbon", aisle: "liquor"),
        Item(word: "broccoli", aisle: "produce"),
        Item(word: "broth", aisle: "soup"),
        Item(word: "brussel", aisle: "produce"),
        Item(word: "buns", aisle: "bread"),
        Item(word: "cabbage", aisle: "produce"),
        Item(word: "caesar", aisle: "pasta"),
        Item(word: "cannellini", aisle: "beans"),
        Item(word: "cantelope", aisle: "produce"),
        Item(word: "carrot", aisle: "produce"),
        Item(word: "cashew", aisle: "bulk"),
        Item(word: "cauliflower", aisle: "produce"),
        Item(word: "celery", aisle: "produce"),
        Item(word: "cereal", aisle: "cereal"),
        Item(word: "chapstick", aisle: "personal"),
        Item(word: "chard", aisle: "produce"),
        Item(word: "cheddar", aisle: "cheese"),
        Item(word: "cheerios", aisle: "cereal"),
        Item(word: "club soda", aisle: "liquor"),
        Item(word: "cognac", aisle: "liquor"),
        Item(word: "couscous", aisle: "bulk"),
        Item(word: "fancy cheese", aisle: "specialty"),
        Item(word: "nice cheese", aisle: "specialty"),
        Item(word: "good cheese", aisle: "specialty"),
        Item(word: "cheese", aisle: "cheese"),
        Item(word: "chicken stock", aisle: "soup"),
        Item(word: "chicken", aisle: "meat"),
        Item(word: "chickpeas", aisle: "beans"),
        Item(word: "chilies", aisle: "beans"),
        Item(word: "fresh chives", aisle: "produce"),
        Item(word: "chives", aisle: "baking"),
        Item(word: "chocolate chips", aisle: "baking"),
        Item(word: "ciabatta", aisle: "specialty"),
        Item(word: "cilantro", aisle: "baking"),
        Item(word: "clean", aisle: "cleaning"),
        Item(word: "cocoa", aisle: "baking"),
        Item(word: "coconut", aisle: "baking"),
        Item(word: "cod", aisle: "seafood"),
        Item(word: "coffee", aisle: "baking"),
        Item(word: "condition", aisle: "personal"),
        Item(word: "corn chips", aisle: "snacks"),
        Item(word: "corn meal", aisle: "baking"),
        Item(word: "corn starch", aisle: "baking"),
        Item(word: "corn tortilla", aisle: "beans"),
        Item(word: "cornmeal", aisle: "baking"),
        Item(word: "cornstarch", aisle: "baking"),
        Item(word: "corn", aisle: "produce"),
        Item(word: "cottage", aisle: "dairy"),
        Item(word: "cough", aisle: "medicine"),
        Item(word: "cranberry", aisle: "pasta"),
        Item(word: "crab", aisle: "seafood"),
        Item(word: "fancy crackers", aisle: "specialty"),
        Item(word: "nice crackers", aisle: "specialty"),
        Item(word: "good crackers", aisle: "specialty"),
        Item(word: "party crackers", aisle: "specialty"),
        Item(word: "crackers", aisle: "snacks"),
        Item(word: "cucumber", aisle: "produce"),
        Item(word: "deli", aisle: "specialty"),
        Item(word: "deod", aisle: "personal"),
        Item(word: "detergent", aisle: "cleaning"),
        Item(word: "diaper", aisle: "babies"),
        Item(word: "dill", aisle: "baking"),
        Item(word: "dressing", aisle: "pasta"),
        Item(word: "dry onion", aisle: "soup"),
        Item(word: "dried", aisle: "snacks"),
        Item(word: "dryer", aisle: "cleaning"),
        Item(word: "eggnog", aisle: "dairy"),
        Item(word: "eggs", aisle: "cheese"),
        Item(word: "evaporated", aisle: "baking"),
        Item(word: "extract", aisle: "baking"),
        Item(word: "feta", aisle: "cheese"),
        Item(word: "filters", aisle: "baking"),
        Item(word: "flour tortilla", aisle: "beans"),
        Item(word: "flour", aisle: "baking"),
        Item(word: "food coloring", aisle: "baking"),
        Item(word: "french bread", aisle: "specialty"),
        Item(word: "garbage bag", aisle: "soup"),
        Item(word: "garbanzo", aisle: "beans"),
        Item(word: "garlic", aisle: "produce"),
        Item(word: "ginger", aisle: "baking"),
        Item(word: "goldfish", aisle: "snacks"),
        Item(word: "graham", aisle: "snacks"),
        Item(word: "granola", aisle: "cereal"),
        Item(word: "grapes", aisle: "produce"),
        Item(word: "green beans", aisle: "produce"),
        Item(word: "hamburgers", aisle: "meat"),
        Item(word: "hoagies", aisle: "bread"),
        Item(word: "honey", aisle: "spreads"),
        Item(word: "hot dogs", aisle: "meat"),
        Item(word: "ibuprof", aisle: "medicine"),
        Item(word: "ice cream", aisle: "freezer"),
        Item(word: "icecream", aisle: "freezer"),
        Item(word: "jack", aisle: "cheese"),
        Item(word: "kale", aisle: "produce"),
        Item(word: "ketchup", aisle: "pasta"),
        Item(word: "lemon juice", aisle: "pasta"),
        Item(word: "lemon", aisle: "produce"),
        Item(word: "lettuce", aisle: "produce"),
        Item(word: "light bulb", aisle: "soup"),
        Item(word: "lightbulb", aisle: "soup"),
        Item(word: "lights", aisle: "soup"),
        Item(word: "lime juice", aisle: "pasta"),
        Item(word: "lime", aisle: "produce"),
        Item(word: "listerine", aisle: "personal"),
        Item(word: "lobster", aisle: "seafood"),
        Item(word: "lunchmeat", aisle: "specialty"),
        Item(word: "lunch meat", aisle: "specialty"),
        Item(word: "macaroni", aisle: "pasta"),
        Item(word: "mayo", aisle: "pasta"),
        Item(word: "makeup", aisle: "personal"),
        Item(word: "marshm", aisle: "baking"),
        Item(word: "marsh m", aisle: "baking"),
        Item(word: "medicine", aisle: "medicine"),
        Item(word: "melen", aisle: "produce"),
        Item(word: "melon", aisle: "produce"),
        Item(word: "mexican bl", aisle: "cheese"),
        Item(word: "mint", aisle: "produce"),
        Item(word: "mouthwash", aisle: "personal"),
        Item(word: "mouth wash", aisle: "personal"),
        Item(word: "mozzarella balls", aisle: "specialty"),
        Item(word: "mozzarella", aisle: "cheese"),
        Item(word: "mushrooms", aisle: "produce"),
        Item(word: "mustard", aisle: "pasta"),
        Item(word: "neospo", aisle: "medicine"),
        Item(word: "noodle", aisle: "pasta"),
        Item(word: "nuts", aisle: "bulk"),
        Item(word: "oatmeal", aisle: "cereal"),
        Item(word: "oats", aisle: "cereal"),
        Item(word: "onion dip", aisle: "snacks"),
        Item(word: "onion", aisle: "produce"),
        Item(word: "oranges", aisle: "produce"),
        Item(word: "oregano", aisle: "baking"),
        Item(word: "orzo", aisle: "pasta"),
        Item(word: "pain", aisle: "medicine"),
        Item(word: "pancake", aisle: "cereal"),
        Item(word: "panko", aisle: "soup"),
        Item(word: "paprika", aisle: "baking"),
        Item(word: "parchment", aisle: "soup"),
        Item(word: "parmesan", aisle: "cheese"),
        Item(word: "parsley", aisle: "baking"),
        Item(word: "parsnip", aisle: "produce"),
        Item(word: "pasta", aisle: "pasta"),
        Item(word: "patties", aisle: "meat"),
        Item(word: "peanut oil", aisle: "baking"),
        Item(word: "peanut", aisle: "spreads"),
        Item(word: "pecans", aisle: "bulk"),
        Item(word: "black pepper", aisle: "baking"),
        Item(word: "pepper spice", aisle: "baking"),
        Item(word: "pepper", aisle: "produce"),
        Item(word: "pie", aisle: "freezer"),
        Item(word: "pita", aisle: "specialty"),
        Item(word: "plastic bag", aisle: "soup"),
        Item(word: "plastic wrap", aisle: "soup"),
        Item(word: "poppy", aisle: "baking"),
        Item(word: "poppyseed", aisle: "baking"),
        Item(word: "pork", aisle: "meat"),
        Item(word: "potato chips", aisle: "snacks"),
        Item(word: "potato", aisle: "produce"),
        Item(word: "provalone", aisle: "cheese"),
        Item(word: "provolone", aisle: "cheese"),
        Item(word: "pumpkins", aisle: "produce"),
        Item(word: "pumpkin", aisle: "baking"),
        Item(word: "pull up", aisle: "babies"),
        Item(word: "pullup", aisle: "babies"),
        Item(word: "quinoa", aisle: "pasta"),
        Item(word: "radish", aisle: "produce"),
        Item(word: "raisen", aisle: "snacks"),
        Item(word: "raison", aisle: "snacks"),
        Item(word: "ramen", aisle: "soup"),
        Item(word: "razor", aisle: "personal"),
        Item(word: "rice", aisle: "bulk"),
        Item(word: "rigatoni", aisle: "pasta"),
        Item(word: "roast", aisle: "meat"),
        Item(word: "root", aisle: "snacks"),
        Item(word: "rosemary", aisle: "baking"),
        Item(word: "salad ingredients", aisle: "produce"),
        Item(word: "salami", aisle: "meat"),
        Item(word: "salmon", aisle: "seafood"),
        Item(word: "salsa", aisle: "produce"),
        Item(word: "salt", aisle: "baking"),
        Item(word: "sausage", aisle: "meat"),
        Item(word: "scallions", aisle: "produce"),
        Item(word: "shallots", aisle: "produce"),
        Item(word: "shampoo", aisle: "personal"),
        Item(word: "shaving", aisle: "personal"),
        Item(word: "shrimp", aisle: "seafood"),
        Item(word: "sour cream", aisle: "cheese"),
        Item(word: "spaghetti", aisle: "pasta"),
        Item(word: "sparkling water", aisle: "snacks"),
        Item(word: "spice", aisle: "baking"),
        Item(word: "spinach", aisle: "produce"),
        Item(word: "sponge", aisle: "cleaning"),
        Item(word: "spring mix salad", aisle: "produce"),
        Item(word: "sprinkles", aisle: "baking"),
        Item(word: "starch", aisle: "baking"),
        Item(word: "steak", aisle: "meat"),
        Item(word: "sugar", aisle: "baking"),
        Item(word: "suppres", aisle: "medicine"),
        Item(word: "syrup", aisle: "cereal"),
        Item(word: "tahini", aisle: "pasta"),
        Item(word: "tampons", aisle: "personal"),
        Item(word: "tenderloin", aisle: "meat"),
        Item(word: "thyme", aisle: "baking"),
        Item(word: "tilapia", aisle: "seafood"),
        Item(word: "tin foil", aisle: "soup"),
        Item(word: "toilet", aisle: "cleaning"),
        Item(word: "diced tomat", aisle: "beans"),
        Item(word: "tomato sauce", aisle: "beans"),
        Item(word: "tomato soup", aisle: "soup"),
        Item(word: "tomato", aisle: "produce"),
        Item(word: "tonic", aisle: "liquor"),
        Item(word: "tooth", aisle: "personal"),
        Item(word: "tortallini", aisle: "pasta"),
        Item(word: "tortellini", aisle: "pasta"),
        Item(word: "tortillini", aisle: "pasta"),
        Item(word: "tortilla chips", aisle: "snacks"),
        Item(word: "tortillas", aisle: "beans"),
        Item(word: "ground turkey", aisle: "meat"),
        Item(word: "turkey", aisle: "specialty"),
        Item(word: "turnip", aisle: "produce"),
        Item(word: "tylenol", aisle: "medicine"),
        Item(word: "veal", aisle: "meat"),
        Item(word: "vegetable oil", aisle: "baking"),
        Item(word: "vegetable", aisle: "produce"),
        Item(word: "vinegar", aisle: "pasta"),
        Item(word: "vitamin water", aisle: "snacks"),
        Item(word: "vitamin", aisle: "medicine"),
        Item(word: "vodka", aisle: "liquor"),
        Item(word: "washer", aisle: "cleaning"),
        Item(word: "weiners", aisle: "meat"),
        Item(word: "whipped", aisle: "dairy"),
        Item(word: "whiskey", aisle: "liquor"),
        Item(word: "windex", aisle: "cleaning"),
        Item(word: "wine", aisle: "liquor"),
        Item(word: "wipes", aisle: "babies"),
        Item(word: "yaki-soba", aisle: "soup"),
        Item(word: "yakisoba", aisle: "soup"),
        Item(word: "yeast", aisle: "baking"),
        Item(word: "yogurt", aisle: "dairy"),
        Item(word: "ziploc", aisle: "soup"),
        Item(word: "zucchini", aisle: "produce"),
        // smaller catch-all words
        Item(word: "baby", aisle: "babies"),
        Item(word: "beans", aisle: "beans"),
        Item(word: "bread", aisle: "bread"),
        Item(word: "butter", aisle: "cheese"),
        Item(word: "chips", aisle: "snacks"),
        Item(word: "cream", aisle: "dairy"),
        Item(word: "eye", aisle: "personal"),
        Item(word: "face", aisle: "personal"),
        Item(word: "fish", aisle: "seafood"),
        Item(word: "fruit", aisle: "produce"),
        Item(word: "gin", aisle: "liquor"),
        Item(word: "hair", aisle: "personal"),
        Item(word: "half", aisle: "dairy"),
        Item(word: "ham", aisle: "specialty"),
        Item(word: "kid", aisle: "babies"),
        Item(word: "lip", aisle: "personal"),
        Item(word: "meat", aisle: "meat"),
        Item(word: "milk", aisle: "dairy"),
        Item(word: "oil", aisle: "baking"),
        Item(word: "pads", aisle: "personal"),
        Item(word: "rum", aisle: "liquor"),
        Item(word: "sauce", aisle: "pasta"),
        Item(word: "soap", aisle: "cleaning"),
        Item(word: "soup", aisle: "soup"),
        Item(word: "tea", aisle: "baking"),
    ]
}
